spring:
  application:
    name:y-ai-code-mother-backend
  session:
    store-type: redis
    timeout: 2592000
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/y_ai_code_mother
    username: root
    password: a600523
  profiles:
    active: local
  # redis
  data:
    redis:
      host: localhost
      port: 6379
      password:
      ttl: 3600
      database: 0


server:
  port: 8000
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000



springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yy.yaicodemother.controller

knife4j:
  enable: true
  setting:
    language: zh_cn
