spring:
  application:
    name:y-ai-code-mother-backend

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/y_ai_code_mother
    username: root
    password: a600523

server:
  port: 8000
  servlet:
    context-path: /api


# springdoc-openapi????
springdoc:
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.yy.yaicodemother.controller
# knife4j???????????????
knife4j:
  enable: true
  setting:
    language: zh_cn
